const constants = {
  GET_TIME: "GET_TIME"
  GET_DATE:"GET_DATE",
  GET_WEATHER:"GET_WEATHER",
  GET_SUNSET:"GET_SUNSET",
  GET_LOCATION:"GET_LOCATION",
  GET_WIND:"GET_WIND",
  GET_SUGGESTIONS:"GET_SUGGESTIONS",
  ADD_ERROR:"ADD_ERROR",
  CLEAR_ERROR:"CLEAR_ERROR",
  CHANGE_SCREEN:"CHANGE_SCREEN",
  CANCEL_SCREEN:"CANCEL_SCREEN"
}

export default constants;
